-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Servidor: 127.0.0.1
-- Tiempo de generación: 04-11-2024 a las 22:25:57
-- Versión del servidor: 10.4.32-MariaDB
-- Versión de PHP: 8.2.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de datos: `juegosdb`
--

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `juegos`
--

CREATE TABLE `juegos` (
  `id` int(11) NOT NULL,
  `titulo` varchar(100) NOT NULL,
  `descripcion` text NOT NULL,
  `imagen_url` varchar(255) NOT NULL,
  `plataformas` varchar(255) NOT NULL,
  `lanzamiento` date NOT NULL,
  `seccion` varchar(50) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Volcado de datos para la tabla `juegos`
--

INSERT INTO `juegos` (`id`, `titulo`, `descripcion`, `imagen_url`, `plataformas`, `lanzamiento`, `seccion`) VALUES
(2, 'Madden NFL 2004', '\"Madden NFL 2004\" es un videojuego de simulación de fútbol americano desarrollado por EA Tiburon y publicado por EA Sports. Lan​zado en 2003, es parte de la serie Madden NFL y se destaca por su jugabilidad realista y gráficos mejorados para su época.El juego incluye modos de juego como franchise, donde los jugadores gestionan equipos a lo largo de múltiples temporadas, y modos de juego rápido que permiten partidos rápidos.\"Madden NFL 2004\" también es conocido por introducir características innovadoras como el modo \"Owner\" y por su banda sonora destacada que incluye música variada y popular.', 'madden_nfl_2004.jpg', 'PlayStation 2, Xbox, GameCube.', '2003-08-12', 'gotys'),
(3, 'Grand Theft Auto: San Andreas', '\"GTA San Andreas\" es un videojuego de acción y aventura lanzado en 2004, parte de la serie Grand Theft Auto. \r\nAmbientado en una versión ficticia de California, conocida como San Andreas, el juego sigue la historia de Carl \"CJ\" Johnson mientras lucha por controlar pandillas y completar misiones en un mundo abierto lleno de libertad y posibilidades. Ofrece una jugabilidad diversa que incluye conducción, combate y exploración en un entorno vasto y detallado.', 'gta_san_andreas.jpg', 'PlayStation 2, Xbox, PC, Xbox 360, PS3.', '2004-10-26', 'gotys'),
(4, 'Resident Evil 4', '\"Resident Evil 4\" es un juego de survival horror lanzado en 2005, parte de la icónica serie Resident Evil. Ambientado en una aldea rural de Europa, sigue al agente especial Leon S. Kennedy en una misión para rescatar a la hija del presidente de los Estados Unidos. El juego se destaca por su acción intensa, atmósfera tensa y sistema de combate mejorado.\"Resident Evil 4\" es aclamado por su innovación en el género, ofreciendo una experiencia inmersiva y emocionante.', 'resident_evil_4.jpg', 'Xbox 360, PS3, PC.', '2005-01-11', 'gotys'),
(5, 'Bioshock', '\"Bioshock\" es un juego de disparos en primera persona lanzado en 2007, conocido por su ambiente único bajo el agua en la ciudad de Rapture. Combina acción intensa con elementos de rol y una narrativa profunda que explora temas como el poder, la moralidad y la manipulación genética.\r\nEl juego es elogiado por su atmósfera inmersiva, diseño de niveles ingenioso y giros en la trama que desafían las expectativas del jugador.', 'bioshock.jpg', ' Xbox 360, PS3, PC.', '2007-08-21', 'gotys'),
(6, 'Grand Theft Auto IV', 'Grand Theft Auto IV (GTA IV) es un videojuego de acción y aventura desarrollado por Rockstar North y lanzado en 2008. La trama sigue a Niko Bellic, un inmigrante de Europa del Este que llega a Liberty City, una ciudad ficticia inspirada en Nueva York, en busca del sueño americano y de su primo Roman. El juego se destaca por su narrativa profunda, personajes complejos y un mundo abierto detallado, donde los jugadores pueden explorar, completar misiones y participar en actividades criminales. GTA IV es conocido por su jugabilidad inmersiva, su diseño gráfico innovador y su crítica social. Además, fue aclamado por la crítica y recibió múltiples premios, consolidándose como uno de los títulos más influyentes de su generación.', 'gta_iv.jpg', 'Xbox 360, PS3, PC.', '2008-04-29', 'gotys'),
(7, 'Uncharted 2: El reino de los ladrones', 'Uncharted 2: Among Thieves es un videojuego de acción y aventura desarrollado por Naughty Dog y lanzado en 2009 para PlayStation 3. Es la secuela de Uncharted: Drake\'s Fortune y sigue las aventuras del cazador de tesoros Nathan Drake mientras busca el mítico Caldero de los Reyes, una antigua reliquia con poderes extraordinarios. El juego combina exploración, resolución de acertijos y intensas secuencias de combate, todo ello en un entorno cinematográfico que incluye escenarios exóticos como montañas cubiertas de nieve y templos antiguos.\r\n\r\nUncharted 2 fue aclamado por su narrativa, personajes carismáticos, gráficos impresionantes y su jugabilidad fluida, consolidándose como uno de los mejores videojuegos de su época. Recibió numerosos premios, incluidos varios Game of the Year, y es considerado un referente en la industria de los videojuegos.', 'uncharted_2.jpg', 'PS3.', '2009-08-13', 'gotys'),
(8, 'Red Dead Redemption', 'Red Dead Redemption es un videojuego de acción y aventura desarrollado por Rockstar San Diego y lanzado en 2010 para PlayStation 3 y Xbox 360. Ambientado en el año 1911, el juego sigue la historia de John Marston, un exforajido que es obligado por el gobierno de los Estados Unidos a capturar a sus antiguos compañeros de banda como parte de un acuerdo para liberar a su familia.\r\n\r\nEl juego se desarrolla en un vasto mundo abierto que recrea el paisaje del Viejo Oeste, permitiendo a los jugadores explorar montañas, praderas y ciudades del suroeste americano. Red Dead Redemption es conocido por su narrativa profunda y emocional, personajes memorables, y un sistema de juego que combina la acción con elementos de rol y exploración.\r\n\r\nEl título fue aclamado por la crítica, recibiendo numerosos premios, incluidos varios Game of the Year. Es ampliamente considerado como uno de los mejores videojuegos de todos los tiempos, destacándose por su rica historia, diseño de mundo y atención al detalle en la representación de la época.', 'red_dead_redemption.jpg', 'Xbox 360, PS3.', '2010-05-18', 'otros'),
(9, 'The Elder Scrolls V: Skyrim', 'The Elder Scrolls V: Skyrim es un videojuego de rol de acción desarrollado por Bethesda Game Studios y lanzado en 2011. Ambientado en la vasta y rica tierra de Skyrim, parte de la serie The Elder Scrolls, el juego permite a los jugadores explorar un mundo abierto lleno de misiones, personajes y una amplia variedad de entornos, desde montañas nevadas hasta bosques densos y ciudades vibrantes.\r\n\r\nLa historia sigue al protagonista, conocido como el Dragonborn, un héroe con la capacidad de absorber el alma de dragones y utilizar poderosos gritos (shouts). Los jugadores pueden personalizar su personaje, elegir entre varias razas y habilidades, y tomar decisiones que afectan el desarrollo de la historia y las relaciones con otros personajes.\r\n\r\nSkyrim es conocido por su libertad de exploración, su rica narrativa, y su profundo sistema de personalización y progresión. El juego ha recibido numerosos premios, incluido el título de Juego del Año, y ha mantenido una base de jugadores activa gracias a su extensa modding community, que continúa ampliando y mejorando la experiencia de juego. Considerado uno de los mejores videojuegos de todos los tiempos, Skyrim ha dejado una huella duradera en la industria del videojuego.', 'skyrim.jpg', 'PC, Xbox 360, PS3, Xbox One, PS4, Nintendo Switch.', '2011-11-11', 'gotys'),
(10, 'The Walking Dead', 'The Walking Dead es un videojuego de aventura interactiva desarrollado por Telltale Games, lanzado en 2012. Basado en la exitosa serie de cómics del mismo nombre, el juego se centra en la historia de Clementine, una joven que intenta sobrevivir en un mundo postapocalíptico infestado de zombis. La narrativa del juego se desarrolla a través de una serie de episodios, donde las decisiones del jugador influyen en la historia y en las relaciones con otros personajes.\r\n\r\nLa jugabilidad se basa en la toma de decisiones, la exploración y la resolución de acertijos, con un enfoque en el desarrollo de personajes y la construcción emocional de la narrativa. A lo largo del juego, los jugadores deben enfrentar dilemas morales difíciles, lo que agrega una capa de profundidad y complejidad a la historia.\r\n\r\nThe Walking Dead fue aclamado por su narrativa impactante, la calidad de sus personajes y la habilidad de Telltale para crear momentos emocionalmente resonantes. Ganó numerosos premios, incluidos varios Game of the Year, y estableció un nuevo estándar para los videojuegos narrativos, influyendo en el desarrollo de otros títulos en el género. La serie continuó con varias secuelas y episodios adicionales, ampliando la historia de Clementine y otros personajes en este mundo devastado.', 'walking_dead.jpg', 'PC, Xbox 360, PS3, iOS, Android.', '2012-04-24', 'gotys'),
(11, 'Grand Theft Auto V (GTA V)', 'Grand Theft Auto V (GTA V) es un videojuego de acción y aventura desarrollado por Rockstar North y lanzado en 2013 para PlayStation 3, Xbox 360, y posteriormente para otras plataformas, incluyendo PlayStation 4, Xbox One y PC. Ambientado en la ficticia ciudad de Los Santos, inspirada en Los Ángeles, el juego presenta un mundo abierto enorme y detallado donde los jugadores pueden explorar, completar misiones y participar en diversas actividades criminales.\r\n\r\nLa narrativa sigue a tres protagonistas: Michael De Santa, un ladrón de bancos retirado; Franklin Clinton, un joven que busca oportunidades en el mundo del crimen; y Trevor Philips, un exmilitar y un sociópata. La historia se desarrolla a través de sus perspectivas, lo que permite a los jugadores alternar entre los personajes y experimentar sus historias interconectadas.\r\n\r\nGTA V es conocido por su jugabilidad expansiva, que incluye una variedad de misiones, actividades secundarias y un modo multijugador en línea, conocido como Grand Theft Auto Online. El juego fue aclamado por su narrativa, personajes memorables, y su detallado diseño de mundo. Ha recibido múltiples premios, incluidos varios Game of the Year, y se ha convertido en uno de los videojuegos más vendidos de todos los tiempos, dejando una huella duradera en la industria y la cultura popular.', 'gta_v.jpg', 'PC, Xbox 360, PS3, Xbox One, PS4.', '2013-09-17', 'gotys'),
(12, 'Dragon Age: Inquisition', 'Dragon Age: Inquisition es un videojuego de rol de acción desarrollado por BioWare, lanzado en 2014. Como la tercera entrega de la serie Dragon Age, el jugador asume el papel del Inquisidor, quien debe restaurar el orden en Thedas tras la aparición de una brecha que permite la entrada de demonios.\r\n\r\nEl juego presenta un mundo abierto con una narrativa rica y decisiones que afectan la historia y las relaciones con otros personajes. Los jugadores pueden crear su propio Inquisidor, eligiendo entre varias razas y clases, y participar en combates en tiempo real.\r\n\r\nAclamado por su profundidad narrativa y gráficos impresionantes, Dragon Age: Inquisition recibió múltiples premios, incluido Game of the Year, consolidándose como uno de los mejores títulos en el género de los videojuegos de rol.', 'dragon_age_inquisition.jpg', ' PC, Xbox 360, PS3, Xbox One, PS4.', '2014-11-18', 'gotys'),
(13, 'The Witcher 3: Wild Hunt', 'The Witcher 3: Wild Hunt es un videojuego de rol de acción desarrollado por CD Projekt Red y lanzado en 2015. Ambientado en un mundo de fantasía detallado y vasto, el juego sigue las aventuras de Geralt de Rivia, un cazador de monstruos conocido como \"witcher,\" mientras busca a su hija adoptiva, Ciri, quien es perseguida por una fuerza misteriosa conocida como la Cacería Salvaje.\r\n\r\nEl juego se caracteriza por su narrativa profunda, misiones complejas y un mundo abierto que permite a los jugadores explorar diversas regiones, interactuar con personajes memorables y tomar decisiones que afectan la historia. Ofrece un sistema de combate dinámico y un extenso árbol de habilidades para personalizar el estilo de juego.\r\n\r\nThe Witcher 3 recibió aclamación crítica por su rica narrativa, desarrollo de personajes, y gráficos impresionantes, ganando numerosos premios, incluido el Game of the Year. Es considerado uno de los mejores videojuegos de todos los tiempos y ha influido significativamente en el género de los RPG.', 'witcher3.jpg', 'PC, Xbox One, PS4, Nintendo Switch.', '2016-05-24', 'gotys'),
(14, 'Overwatch', 'Overwatch es un videojuego de disparos en equipo en primera persona desarrollado por Blizzard Entertainment y lanzado en 2016. Ambientado en un futuro cercano, el juego presenta un mundo donde los jugadores eligen entre una variedad de héroes, cada uno con habilidades únicas y roles específicos, como atacante, defensor, tanque y soporte.\r\n\r\nEl juego se centra en el trabajo en equipo y la estrategia, con modos de juego que incluyen capturar objetivos y escortar cargas. Overwatch destaca por su vibrante estilo artístico, su diversa representación de personajes y su narrativa expandida a través de cortometrajes animados y cómics.\r\n\r\nDesde su lanzamiento, Overwatch ha sido aclamado por su jugabilidad adictiva, el diseño de personajes y su enfoque en el juego en equipo. Ha recibido varios premios, incluidos Game of the Year, y ha mantenido una activa comunidad de jugadores, así como una liga competitiva profesional, la Overwatch League.', 'overwatch.jpg', ' PC, Xbox One, PS4, Nintendo Switch.', '2016-05-24', 'gotys'),
(15, 'The Legend of Zelda: Breath of the Wild', 'The Legend of Zelda: Breath of the Wild es un videojuego de acción y aventura desarrollado por Nintendo y lanzado en 2017 para la consola Nintendo Switch y Wii U. Ambientado en un vasto mundo abierto, el juego sigue a Link, quien despierta de un largo sueño para enfrentarse a Calamity Ganon y salvar el reino de Hyrule.\r\n\r\nBreath of the Wild se destaca por su exploración no lineal, donde los jugadores pueden abordar misiones y desafíos en el orden que deseen. El juego introduce un sistema de física avanzado, lo que permite diversas interacciones con el entorno, como escalar montañas, cocinar alimentos y resolver acertijos.\r\n\r\nAclamado por su diseño de mundo, libertad de juego y atención al detalle, Breath of the Wild recibió numerosos premios, incluidos varios Game of the Year, y es considerado uno de los mejores videojuegos de todos los tiempos, redefiniendo el género de los juegos de aventura y estableciendo un nuevo estándar para futuros títulos de la serie.', 'zelda_breath_of_the_wild.jpg', 'Nintendo Switch, Wii U.', '2017-03-03', 'gotys'),
(16, 'God of War', 'God of War es un videojuego de acción y aventura desarrollado por Santa Monica Studio y lanzado en 2018 para PlayStation 4. Esta entrega es una reinvención de la popular franquicia, centrada en Kratos, el antiguo dios de la guerra, que ahora vive en un mundo inspirado en la mitología nórdica y ha asumido un papel de padre al cuidar de su hijo, Atreus.\r\n\r\nLa narrativa sigue a Kratos y Atreus en su viaje para esparcir las cenizas de la madre de Atreus en la cima de la montaña más alta de los reinos. El juego combina elementos de acción y exploración con una profunda historia centrada en la relación entre padre e hijo, así como en temas de redención y legado.\r\n\r\nGod of War es conocido por su impresionante diseño visual, jugabilidad fluida y un sistema de combate renovado que incluye el uso del hacha Leviatán. Fue aclamado por la crítica, recibiendo numerosos premios, incluido el Game of the Year, y se considera uno de los mejores videojuegos de la generación de consolas, destacándose por su narrativa emocional y su innovación en la serie.\r\n\r\n\r\n\r\n\r\n\r\n\r\n', 'god_of_war.jpg', 'PS4.', '2018-04-20', 'gotys'),
(17, 'Sekiro: Shadows Die Twice', 'Sekiro: Shadows Die Twice es un videojuego de acción y aventura desarrollado por FromSoftware y lanzado en 2019. Ambientado en un Japón feudal ficticio, el juego sigue la historia de un guerrero llamado Sekiro, también conocido como \"El Lobo,\" que busca rescatar a su joven maestro y vengar su deshonra.\r\n\r\nEl juego se destaca por su enfoque en el combate preciso y estratégico, que combina el uso de espadas y habilidades de sigilo. A diferencia de otros títulos de FromSoftware, Sekiro no permite personalización del personaje ni construcción de clases, centrándose en la habilidad del jugador y la mecánica de posturas, donde romper la guardia del enemigo es clave para ganar.\r\n\r\nSekiro es conocido por su dificultad desafiante, diseño de niveles intrincado y su narrativa inmersiva, así como por su estilo artístico y la atención al detalle en su ambientación. Aclamado por la crítica, ganó numerosos premios, incluido el Game of the Year en varios certámenes, y es considerado uno de los mejores videojuegos de su generación, destacándose por su innovador enfoque en el combate y su rica historia.', 'sekiro.jpg', 'PC, Xbox One, PS4.', '2018-04-20', 'gotys'),
(18, 'The Last of Us Part II', '\r\nThe Last of Us Part II es un videojuego de acción y aventura desarrollado por Naughty Dog y lanzado en 2020 para PlayStation 4. Continuación del aclamado The Last of Us, el juego se sitúa en un mundo postapocalíptico donde los jugadores siguen la historia de Ellie, ahora una joven adulta, mientras busca venganza tras un trágico evento que afecta su vida y su relación con Joel, su protector y figura paterna.\r\n\r\nEl juego es conocido por su narrativa emocionalmente intensa, que explora temas de pérdida, odio y redención. La jugabilidad combina sigilo, combate y exploración, con un enfoque en la supervivencia en un mundo hostil lleno de humanos y criaturas infectadas.\r\n\r\nThe Last of Us Part II fue aclamado por la crítica, recibiendo numerosos premios, incluidos varios Game of the Year, y es elogiado por su enfoque en la representación de personajes, su diseño artístico y su poderosa historia. Sin embargo, también generó controversia entre algunos fanáticos, lo que provocó debates sobre su narrativa y decisiones de diseño. A pesar de esto, se considera uno de los mejores videojuegos de su generación.', 'last_of_us_part_ii.jpg', 'PS4.', '2020-06-19', 'gotys'),
(19, 'It Takes Two', 'It Takes Two es un videojuego de acción y aventura cooperativa desarrollado por Hazelight Studios y lanzado en 2021. Diseñado específicamente para ser jugado en modo cooperativo, ya sea en línea o en pantalla dividida, el juego sigue la historia de Cody y May, una pareja en proceso de divorcio que se transforma en muñecos después de que su hija, Rose, desea que se reconcilien.\r\n\r\nA lo largo del juego, los jugadores deben trabajar juntos para superar una variedad de desafíos y acertijos en un mundo colorido y creativo, donde cada nivel presenta nuevas mecánicas de juego que requieren cooperación y comunicación. La narrativa se centra en la importancia del trabajo en equipo y la conexión emocional entre los personajes.\r\n\r\nIt Takes Two fue aclamado por su innovador diseño de juego, creatividad y enfoque en la colaboración. Ganó varios premios, incluido el Game of the Year en los Game Awards, y es considerado uno de los mejores videojuegos cooperativos de todos los tiempos, destacándose por su capacidad de unir a los jugadores en una experiencia compartida y divertida.', 'it_takes_two.jpg', 'PC, Xbox One, PS4, Xbox Series X/S, PS5.', '2011-03-26', 'gotys'),
(20, 'Elden Ring', 'Elden Ring es un videojuego de rol de acción desarrollado por FromSoftware y lanzado en 2022. Ambientado en un mundo abierto llamado The Lands Between, el juego combina elementos de exploración, combate y narrativa, con un diseño que recuerda a otros títulos de FromSoftware como Dark Souls y Bloodborne, pero con una escala mucho mayor.\r\n\r\nLos jugadores asumen el papel de un \"Tarnished\", un personaje que busca restaurar el Elden Ring y convertirse en el Elden Lord. La jugabilidad se centra en un combate desafiante, donde se pueden utilizar una variedad de armas, magia y habilidades, junto con un sistema de progresión que permite a los jugadores personalizar sus personajes de diferentes maneras.\r\n\r\nElden Ring ha sido aclamado por su vasto mundo abierto, su rica narrativa y la libertad que ofrece a los jugadores para explorar y enfrentar desafíos a su propio ritmo. La colaboración con el autor George R.R. Martin para el desarrollo del mundo y la historia también ha sido un punto destacado. El juego recibió múltiples premios, incluido el Game of the Year, y es considerado uno de los mejores videojuegos de la década, elogiado por su diseño, profundidad y complejidad.', 'elden_ring.jpg', 'PC, Xbox One, PS4, Xbox Series X/S, PS5.', '2022-02-25', 'gotys'),
(21, 'Baldur\'s Gate 3 ', 'Baldur\'s Gate 3 es un videojuego de rol desarrollado por Larian Studios y lanzado en acceso anticipado en 2020, con su versión completa lanzada en 2023. Basado en el universo de Dungeons & Dragons, el juego se sitúa en la ciudad de Baldur\'s Gate y sus alrededores, donde los jugadores crean su propio personaje y se embarcan en una aventura épica llena de exploración, combate táctico y toma de decisiones.\r\n\r\nEl juego presenta un enfoque en la narrativa, permitiendo a los jugadores tomar decisiones que afectan el desarrollo de la historia y las relaciones con los personajes no jugables (PNJ). El sistema de combate es por turnos, ofreciendo una experiencia estratégica que se adapta a las reglas de Dungeons & Dragons.\r\n\r\nBaldur\'s Gate 3 ha sido aclamado por su rica narrativa, personajes bien desarrollados, y su jugabilidad profunda y envolvente. La atención al detalle, la calidad de los gráficos y el diseño de los escenarios han sido especialmente elogiados. Considerado como un hito en el género de los RPG, ha recibido numerosos premios y se destaca por revitalizar la serie Baldur\'s Gate, capturando tanto a los fanáticos de la saga como a nuevos jugadores.', 'baldurs_gate_3.jpg', 'PC, Stadia.', '2023-10-06', 'gotys'),
(22, 'Assassin\'s Creed Unity', 'Assassin\'s Creed Unity es un videojuego de acción y aventura desarrollado por Ubisoft y lanzado en 2014 para PlayStation 4, Xbox One y PC. Ambientado en París durante la Revolución Francesa, el juego sigue la historia de Arno Dorian, un joven que se une a la hermandad de los Asesinos para descubrir la verdad detrás de la muerte de su padre adoptivo y buscar venganza.\r\n\r\nUnity se destaca por su enfoque en la exploración de un mundo abierto detallado, que permite a los jugadores experimentar la vibrante ciudad de París y sus emblemáticos monumentos, como la Catedral de Notre-Dame y el Palacio de Versalles. El juego introduce un sistema de personalización de personajes, así como un renovado enfoque en el sigilo y el combate, permitiendo a los jugadores adaptar sus habilidades y equipamiento.\r\n\r\nEl título también fue pionero en el modo multijugador cooperativo, donde hasta cuatro jugadores pueden completar misiones juntos. Aunque el juego recibió críticas mixtas en su lanzamiento debido a problemas técnicos y bugs, fue elogiado por su diseño visual y su representación histórica. A lo largo del tiempo, Assassin\'s Creed Unity ha sido reevaluado positivamente por su rica narrativa y su enfoque en el desarrollo del mundo y los personajes.', 'game3.jpg', 'PlayStation 4, Xbox One y PC. ', '2014-11-11', 'otros'),
(23, 'Red Dead Redemption', 'Red Dead Redemption es un videojuego de acción y aventura desarrollado por Rockstar San Diego y lanzado el 18 de mayo de 2010 para PlayStation 3 y Xbox 360. Ambientado en un mundo abierto que recrea el Viejo Oeste americano, el juego sigue la historia de John Marston, un exforajido que busca redención y debe rastrear a sus antiguos compañeros de banda para liberar a su familia, que ha sido secuestrada por el gobierno.\r\n\r\nEl juego se caracteriza por su narrativa profunda, personajes memorables y una jugabilidad que combina exploración, combate, y actividades como caza, pesca y duelos. La ambientación detallada y la atención al realismo en la representación del entorno del Viejo Oeste contribuyen a la inmersión del jugador.\r\n\r\nRed Dead Redemption fue aclamado por la crítica, recibiendo múltiples premios, incluidos varios Game of the Year, y es considerado uno de los mejores videojuegos de todos los tiempos, destacándose por su rica narrativa y su impacto en la industria de los videojuegos.', 'red_dead_redemption2.jpg', 'PlayStation 3 y Xbox 360.', '2010-05-18', 'otros'),
(24, 'Resident Evil 8', 'Resident Evil Village, también conocido como Resident Evil 8, es un videojuego de horror de supervivencia desarrollado por Capcom y lanzado el 7 de mayo de 2021. Continuación de Resident Evil 7: Biohazard, el juego sigue la historia de Ethan Winters, quien viaja a un misterioso pueblo en Europa en busca de su hija secuestrada, enfrentándose a diversos enemigos, incluyendo a la icónica Lady Dimitrescu y sus hijas, así como a otras criaturas sobrenaturales.\r\n\r\nAmbientado en un entorno rural y oscuro, Resident Evil Village combina elementos de horror, exploración y acción, ofreciendo una experiencia en primera persona. El juego introduce mecánicas de combate mejoradas y una mayor variedad de enemigos, así como la posibilidad de personalizar y mejorar las armas.\r\n\r\nResident Evil Village ha sido aclamado por su narrativa envolvente, diseño visual impresionante y la mezcla de horror y acción, recibiendo varios premios, incluido el de \"Juego del Año\" en algunos certámenes. Es considerado uno de los mejores títulos de la serie Resident Evil, manteniendo la tradición de la franquicia mientras introduce nuevos elementos innovadores.', 'resident_evil_8.jpg', 'PC, PS4, PS5, Xbox One, Xbox Series X/S.', '2021-05-07', 'otros'),
(25, 'Bloodborne', 'Bloodborne es un videojuego de rol de acción desarrollado por FromSoftware y lanzado en marzo de 2015 exclusivamente para PlayStation 4. Ambientado en la oscura y gótica ciudad de Yharnam, el juego sigue a un cazador que busca respuestas sobre una extraña enfermedad que afecta a la población y se enfrenta a diversas criaturas sobrenaturales y horrores indescriptibles.\r\n\r\nEl juego se destaca por su jugabilidad rápida y agresiva, que fomenta un estilo de combate ofensivo. A diferencia de otros títulos de FromSoftware, Bloodborne introduce un sistema de regeneración de salud que permite a los jugadores recuperar vida al atacar a los enemigos después de haber sido heridos, lo que añade una capa de estrategia al combate.\r\n\r\nBloodborne es conocido por su atmósfera sombría, diseño artístico detallado y narrativa profunda, que se cuenta a través de la exploración y la interacción con personajes no jugables. Aclamado por la crítica, recibió numerosos premios, incluido el de \"Juego del Año\", y es considerado uno de los mejores videojuegos de su generación, influyendo en el desarrollo de otros títulos en el género de horror y acción.', 'bloodborne.jpg', 'PS4.', '2015-03-24', 'otros'),
(26, 'Doom Eternal', 'Doom Eternal es un videojuego de disparos en primera persona desarrollado por id Software y lanzado el 20 de marzo de 2020. Es la secuela de Doom (2016) y continúa la historia del Doom Slayer, quien se enfrenta a una invasión demoníaca de la Tierra y a nuevos enemigos que amenazan la humanidad.\r\n\r\nEl juego se caracteriza por su jugabilidad rápida y fluida, donde los jugadores deben utilizar una combinación de armas, movimientos y habilidades para derrotar a hordas de enemigos en entornos expansivos y variados. Doom Eternal introduce nuevos elementos de juego, como el sistema de \"desmembramiento\" y la posibilidad de realizar ejecuciones espectaculares para obtener recursos, lo que aumenta la sensación de poder y dinamismo.\r\n\r\nCon un enfoque en la acción constante, el juego también ofrece una narrativa más desarrollada que explora la historia del Doom Slayer y el universo de Doom. Doom Eternal recibió aclamación por su diseño de niveles, mecánicas de combate y gráficos impresionantes, ganando varios premios, incluido el de \"Mejor Juego de Acción\" y \"Juego del Año\" en algunos certámenes, consolidándose como uno de los mejores títulos de la serie y del género de disparos en primera persona.', 'doom_eternal.jpg', 'PC, PS4, Xbox One, Nintendo Switch.', '2020-03-20', 'otros'),
(27, 'God of War Ragnarok', 'God of War Ragnarök es un videojuego de acción y aventura desarrollado por Santa Monica Studio y lanzado el 9 de noviembre de 2022 para PlayStation 4 y PlayStation 5. Continuación de God of War (2018), el juego sigue la historia de Kratos y su hijo Atreus mientras navegan por los desafíos que plantea el inminente Ragnarök, un evento apocalíptico en la mitología nórdica.\r\n\r\nEl juego expande la narrativa de la serie, profundizando en la relación entre padre e hijo y explorando temas de legado, responsabilidad y sacrificio. Los jugadores pueden explorar nuevos reinos, enfrentarse a diversos enemigos, incluyendo dioses y criaturas mitológicas, y utilizar un arsenal de habilidades y armas mejoradas, como el hacha Leviatán y las Espadas del Caos.\r\n\r\nGod of War Ragnarök ha sido aclamado por su impresionante diseño visual, su narrativa rica y emotiva, así como por su jugabilidad fluida. La crítica ha elogiado la profundidad de sus personajes y el desarrollo de la historia, y el juego ha ganado numerosos premios, incluido el de \"Juego del Año\" en varios eventos. Se considera un hito en la franquicia y un ejemplo destacado de cómo los videojuegos pueden contar historias significativas y emocionales.', 'god_of_war_ragnarok.jpg', 'PS4 y PS5.', '2022-11-09', 'otros'),
(28, 'Xenoblade 3', 'Xenoblade Chronicles 3 es un videojuego de rol de acción desarrollado por Monolith Soft y lanzado el 29 de julio de 2022 para Nintendo Switch. La tercera entrega de la serie Xenoblade Chronicles combina elementos de exploración, combate y narrativa en un mundo vasto y detallado, ambientado en el continente de Aionios, donde dos naciones en guerra, Keves y Agnus, luchan por la supremacía.\r\n\r\nLa historia sigue a un grupo de personajes conocidos como \"Los Protagonistas,\" que incluyen a Noah, Mio, Lanz, Sena, y otros, quienes deben unirse para descubrir la verdad detrás de su mundo y las fuerzas que lo amenazan. El juego introduce un sistema de combate dinámico y estratégico que combina ataques automáticos con habilidades especiales, y permite a los jugadores cambiar entre diferentes clases de personajes durante el combate.\r\n\r\nXenoblade Chronicles 3 ha sido aclamado por su rica narrativa, desarrollo de personajes, y su amplia exploración del mundo, así como por su sistema de combate mejorado y la presentación visual. La crítica ha elogiado la profundidad de su historia y la forma en que se conecta con los eventos de las entregas anteriores, consolidándolo como uno de los mejores títulos en la serie y en el género de los RPG en general.', 'xenoblade_3.jpg', 'Nintendo Switch.', '2022-07-29', 'otros'),
(29, 'Hades', 'Hades es un videojuego de acción roguelike desarrollado por Supergiant Games y lanzado en acceso anticipado en 2018, con su lanzamiento completo en 2020. Ambientado en el inframundo de la mitología griega, el jugador asume el papel de Zagreus, el hijo del dios Hades, quien busca escapar del inframundo para encontrar a su madre, Perséfone.\r\n\r\nEl juego se destaca por su estilo artístico impresionante, narración envolvente y mecánicas de combate fluidas y dinámicas. A medida que los jugadores avanzan, deben enfrentarse a una variedad de enemigos y jefes, cada vez más desafiantes, mientras recolectan poderosas habilidades y mejoras conocidas como \"boons\" otorgadas por otros dioses del Olimpo.\r\n\r\nUna de las características más aclamadas de Hades es su enfoque en la narrativa, que se desarrolla a través de diálogos y encuentros repetidos con personajes que evolucionan con cada intento de escape. Este sistema de progresión permite a los jugadores experimentar nuevas historias y desarrollos de personajes en cada partida.\r\n\r\nHades ha sido ampliamente elogiado por su jugabilidad, diseño y escritura, recibiendo numerosos premios, incluido el de \"Juego del Año\" en varios certámenes. Se considera uno de los mejores títulos en el género roguelike y un destacado ejemplo de cómo se pueden contar historias profundas y emotivas en un videojuego.', 'hades.jpg', 'PC, Nintendo Switch.', '2020-09-17', 'otros'),
(30, 'Fallout 4', 'Fallout 4 es un videojuego de rol de acción desarrollado por Bethesda Game Studios y lanzado el 10 de noviembre de 2015. Ambientado en un mundo postapocalíptico tras una guerra nuclear, el juego tiene lugar en el área de Boston, conocida como la Commonwealth, y sigue la historia del \"Sole Survivor,\" quien emerge de un refugio subterráneo (Vault) 200 años después del desastre.\r\n\r\nEl jugador asume el rol del protagonista en su búsqueda para encontrar a su hijo desaparecido, mientras navega por un mundo abierto lleno de peligros, facciones en conflicto y criaturas mutantes. Fallout 4 introduce un sistema de combate en tiempo real, así como un enfoque en la construcción de asentamientos, permitiendo a los jugadores crear y personalizar refugios y comunidades.\r\n\r\nEl juego es conocido por su rica narrativa, exploración expansiva, y la profundidad de sus personajes y misiones secundarias. Los jugadores pueden interactuar con diversas facciones, tomar decisiones que afectan el curso de la historia, y personalizar su personaje a través de un sistema de habilidades y perks.\r\n\r\nFallout 4 recibió críticas generalmente positivas, siendo elogiado por su inmersivo mundo abierto y la libertad que ofrece a los jugadores, aunque algunos señalaron problemas técnicos y un enfoque en la acción que diferenciaba a este título de sus predecesores. A pesar de las críticas, se consolidó como uno de los juegos más populares de la serie y ha mantenido una activa comunidad de modding y expansión.', 'fallout_4.jpg', ' PC, PS4, Xbox One.', '2015-11-10', 'otros'),
(31, 'Nier Automata', 'NieR: Automata es un videojuego de rol de acción desarrollado por PlatinumGames y publicado por Square Enix, lanzado en marzo de 2017. Ambientado en un mundo postapocalíptico, el juego sigue la historia de seres artificiales, específicamente androides, que luchan en una guerra entre humanos y máquinas. La narrativa se centra en tres protagonistas: 2B, un androide de combate; 9S, un androide de exploración; y A2, un androide rebelde.\r\n\r\nEl juego combina elementos de combate rápido y fluido con mecánicas de plataformas y exploración en un entorno de mundo abierto. NieR: Automata es conocido por su profunda y compleja narrativa que aborda temas de existencia, conciencia, y el sentido de la vida, así como por su enfoque filosófico y emocional.\r\n\r\nLa música, compuesta por Keiichi Okabe, ha sido ampliamente elogiada, contribuyendo a la atmósfera inmersiva del juego. NieR: Automata también presenta múltiples finales que requieren que los jugadores jueguen a través de la historia varias veces para desvelar toda la trama.\r\n\r\nRecibió críticas muy positivas por su diseño artístico, jugabilidad, y narrativa, consolidándose como uno de los mejores videojuegos de la década. Ganó varios premios, incluido el de \"Mejor Juego del Año\" en ciertos certámenes, y ha desarrollado una base de fans apasionada que continúa analizando sus temas y contenido.', 'nier_automata.jpg', 'PC, PS4, Xbox One.', '2017-02-23', 'otros'),
(32, 'Stardew Valley', 'Stardew Valley es un videojuego de simulación de granja desarrollado por ConcernedApe, lanzado el 26 de febrero de 2016. En el juego, los jugadores asumen el papel de un personaje que hereda una granja en el tranquilo pueblo de Pelican Town y deben restaurarla mientras interactúan con los habitantes locales, cultivan cosechas, crían animales, y participan en diversas actividades comunitarias.\r\n\r\nEl juego combina elementos de agricultura, minería, pesca y artesanía, permitiendo a los jugadores personalizar su granja y desarrollar sus habilidades a lo largo del tiempo. Stardew Valley también incluye un sistema de relaciones, donde los jugadores pueden forjar amistades e incluso casarse con algunos de los personajes del pueblo.\r\n\r\nSu estilo gráfico pixelado y su música relajante contribuyen a una atmósfera encantadora y nostálgica. Stardew Valley ha sido aclamado por su jugabilidad adictiva, profundidad y la libertad que ofrece a los jugadores para jugar a su propio ritmo.\r\n\r\nDesde su lanzamiento, el juego ha recibido varias actualizaciones que han añadido nuevo contenido y características, y ha sido elogiado tanto por la crítica como por los jugadores, convirtiéndose en un título emblemático en el género de simulación y gestión de granjas. También ha generado una activa comunidad de modding que ha expandido aún más la experiencia del juego.', 'stardew_valley.jpg', 'PC, PS4, Xbox One, Nintendo Switch, iOS, Android.', '2016-02-26', 'otros'),
(33, 'Honkai Stail Rail', 'Honkai: Star Rail es un videojuego de rol y estrategia por turnos desarrollado por HoYoverse, lanzado el 26 de abril de 2023. Forma parte de la serie Honkai y ofrece a los jugadores una experiencia de juego en un entorno espacial, donde exploran diferentes mundos y se enfrentan a diversas amenazas.\r\n\r\nEl juego se centra en un grupo de personajes llamados \"Trailblazers\" que viajan a bordo del tren astral llamado \"Astral Express\". Los jugadores forman un equipo con diferentes personajes, cada uno con habilidades únicas y estilos de combate, para enfrentar enemigos en batallas estratégicas por turnos. A medida que avanzan en la historia, los jugadores descubren una narrativa rica y compleja, con elementos de exploración y desarrollo de personajes.\r\n\r\nHonkai: Star Rail es conocido por su hermoso diseño visual, su narrativa inmersiva y su sistema de combate dinámico. La música y el estilo artístico también han sido ampliamente elogiados. A lo largo del tiempo, el juego ha expandido su contenido a través de actualizaciones, introduciendo nuevos personajes, historias y misiones, lo que ha mantenido el interés de la comunidad de jugadores. Al igual que otros títulos de HoYoverse, ha generado una base de fans apasionada y activa, contribuyendo al éxito de la franquicia.', 'honkai_stail_rail.jpg', 'PC, PS4, iOS, Android.', '2023-04-26', 'otros'),
(34, 'Titanfall 2', 'Titanfall 2 es un videojuego de disparos en primera persona desarrollado por Respawn Entertainment y lanzado el 28 de octubre de 2016. Es la secuela de Titanfall (2014) y continúa la jugabilidad centrada en la combinación de combate a pie y el uso de gigantescos mechas llamados \"Titans\".\r\n\r\nEl juego presenta una campaña para un jugador que sigue la historia de Jack Cooper, un piloto de élite que se convierte en el compañero de un Titan llamado BT-7274. La narrativa se centra en su lucha contra las fuerzas de la IMC en un conflicto intergaláctico, y la campaña ha sido elogiada por su diseño de niveles innovador, mecánicas de juego fluidas y desarrollo de personajes.\r\n\r\nAdemás de la campaña, Titanfall 2 también incluye un robusto modo multijugador, que ofrece diversas modalidades de juego y una amplia personalización de Titans y pilotos. La mezcla de velocidad, verticalidad y estrategia en el combate ha sido aclamada por la crítica, estableciendo a Titanfall 2 como un referente en el género de los shooters.\r\n\r\nA pesar de su éxito crítico, el juego enfrentó una dura competencia en su lanzamiento, lo que resultó en ventas más bajas de lo esperado. Sin embargo, con el tiempo, Titanfall 2 ha cultivado una base de fans leal y se ha ganado un lugar destacado en la historia de los videojuegos como uno de los mejores shooters de su generación.', 'titanfall_2.jpg', 'PC, Xbox One, PS4.', '2016-10-28', 'otros');

--
-- Índices para tablas volcadas
--

--
-- Indices de la tabla `juegos`
--
ALTER TABLE `juegos`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT de las tablas volcadas
--

--
-- AUTO_INCREMENT de la tabla `juegos`
--
ALTER TABLE `juegos`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=35;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
